# --- !Ups

create table "people"(
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table "user"(
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "email" varchar not null,
  "is_active" bit not null
);

create table "group"(
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "is_active" bit not null
);

create table "user_group"(
  "user_id" bigint not null,
  "group_id" bigint not null,
  constraint user_fk foreign key ("user_id") references public."user"("id"),
  constraint group_fk foreign key ("group_id") references public."group"("id")
);

# --- !Downs

drop table "people" if exists;
drop table "user_group" if exists;
drop table "group" if exists;
drop table "user" if exists;

